### ISSUE TITLE
Show the maximum frame rate during ROI calibration

### ISSUE THREAD

**Issue by vero-npm** [neurophotometrics/neurophotometrics#7]
it would be very helpful to have a feature in bonsai whereby we can see what the max framerate is for a given set of ROIs/field of view

**Comment by glopesdev** [comment]
This is probably easiest and most useful to show during ROI calibration, probably in a status bar at the bottom, we can include it in the next release.

**Comment by glopesdev** [comment]
It turns out it is not possible to know the maximum effective frame rate during live calibration, as the spinnaker camera ROI configuration can only be changed while acquisition is completely stopped (pausing is also not enough). This makes it harder to implement this feature as we would have to reinitialize the capture stream during ROI editing.

A practical alternative is to include the achievable maximum frame rate in the error message in case the system cannot match the requested frequency. This would indicate how far one is from the desired frame rate along with some tips on how to improve the bandwidth.

**Comment by glopesdev** [comment]
Changing the binning mode to additive doubled the default effective frame rate on full-frame to 157 Hz so I don't think we need to worry about this at all from now on.
